/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_mfccnative_MFCCLib */

#ifndef _Included_com_android_mfccnative_MFCCLib
#define _Included_com_android_mfccnative_MFCCLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_mfccnative_MFCCLib
 * Method:    mfcc
 * Signature: ([D[D[D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_android_mfccnative_MFCCLib_mfcc
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
